spring:
  application:
    name: client-post
  profiles:
    active: devel
  datasource:
    url: jdbc:mysql://localhost:3306/blog
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    testOnBorrow: true
    validationQuery: SELECT 1
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
eureka:
  client:
    service-url:
      default-zone: http://localhost:8090/eureka/
server:
  port: 8081